# Generated by Django 3.1.5 on 2022-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20220611_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_class',
            field=models.CharField(default='Any', max_length=50),
        ),
    ]
